### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by Jam1zhu** [weex-plugins/weex-app-seed#1]
```bash
weexpack run ios             // iOS project not found !
```
运行 weexpack init 没反应，也不起作用

```bash
weexpack platform list 
weexpack platform add ios 
```
查看平台列表或者添加列表报错
`Error: Current working directory is not a weexpack project.`

**Comment by JackPu** [comment]
你进入目录后再执行命令吧?
![image](https://cloud.githubusercontent.com/assets/4744967/23740561/195f2ffe-04df-11e7-9f05-82f276ae148c.png)

**Comment by Jam1zhu** [comment]
@JackPu 应该是吧。直接复制粘贴的**如何使用**里的代码。可能是什么问题呐？

<img width="660" alt="aa5f21e3-704e-45ef-97b0-30dc512b8155" src="https://cloud.githubusercontent.com/assets/21252750/23779203/04a8f1e4-057a-11e7-83f3-08609e0fb7b5.png">

**Comment by JackPu** [comment]
Hello 你试下 这个命令 让weeexpack 支持vue
``` bash
git clone https://github.com/weexteam/weex-pack 
git checkout -b vue2.0 origin/vue2.0
cd   weex-pack  && npm link
```

**Comment by zhiweiofli** [comment]
/weex/weex-app-seed   master ●  weexpack run web
module.js:471
    throw err;
    ^

Error: Cannot find module 'ip'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by zhiweiofli** [comment]
还是跑不起来

**Comment by JackPu** [comment]
@zhiweiofli  你安装下依赖 

``` bash
npm i ip --save-dev
```

**Comment by py389172739** [comment]
@JackPu 项目跑起来后在android端看不到底部的导航条

**Comment by JackPu** [comment]
@zhiweiofli  你是 windows么？

**Comment by JackPu** [comment]
@py389172739  提供下你的机型？

**Comment by py389172739** [comment]
@JackPu  我的windows系统，手机型号：华为畅享5s
